version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  
  pre_build:
    commands:
      - echo "Starting backend deployment..."
      - echo "Installing dependencies if needed..."
      - pip install boto3

  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      # Deploys the infrastructure, ensuring resources exist.
      - aws cloudformation deploy --template-file infra/secureview-backend.yml --stack-name SecureViewBackend --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      
      - echo "Zipping and deploying Bedrock Categorization Lambda..."
      - cd backend/lambda/bedrock
      - zip -r ../bedrock.zip .
      - cd ../../..
      - aws lambda update-function-code --function-name svCategorizeURL --zip-file fileb://backend/lambda/bedrock.zip

      - echo "Zipping and deploying Email Report Lambda..."
      - cd backend/lambda/send_email
      - zip -r ../email.zip .
      - cd ../../..
      - aws lambda update-function-code --function-name svSendEmailReport --zip-file fileb://backend/lambda/email.zip

      - echo "Zipping and deploying Edge Lambda (Categorization Auth)..."
      - cd backend/lambda
      - zip -r edge.zip lambda_function.py
      - cd ../..
      - aws lambda update-function-code --function-name svSignedCategorizeRequest --zip-file fileb://backend/lambda/edge.zip

  post_build:
    commands:
      - echo "Backend deployment complete!"
